baseURL = 'https://kreatorsguild.org'
languageCode = 'en-us'
title = "Kreators Guild Inc."
theme = 'ananke'

[params]
  text_color = ""
  body_classes = "sans-serif bg-white"
  author = ""
  favicon = ""
  site_logo = ""
  recent_posts_number = 3
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
